server:
  port: 8888
spring:
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.110:8848
    gateway:
      routes:
        - id: novel-home-front
          uri: lb://novel-home-service
          predicates:
            - Path=/api/front/home/**
        - id: novel-news-front
          uri: lb://novel-news-service
          predicates:
            - Path=/api/front/news/**
        - id: novel-resource-front
          uri: lb://novel-resource-service
          predicates:
            - Path=/api/front/resource/**
        - id: novel-resource-image
          uri: lb://novel-resource-service
          predicates:
            - Path=/image/**
        - id: novel-user-front
          uri: lb://novel-user-service
          predicates:
            - Path=/api/front/user/**
        - id: novel-book-front
          uri: lb://novel-book-service
          predicates:
            - Path=/api/front/book/**
        - id: novel-search-front
          uri: lb://novel-search-service
          predicates:
            - Path=/api/front/search/**
        - id: novel-author
          uri: lb://novel-author-service
          predicates:
            - Path=/api/author/**

# Actuator 端点管理
management:
  # 端点公开配置
  endpoints:
    # 通过 HTTP 公开的 Web 端点
    web:
      exposure:
        # 公开所有的 Web 端点
        include: "*"
  # 端点启用配置
  endpoint:
    logfile:
      # 启用返回日志文件内容的端点
      enabled: true
      # 外部日志文件路径
      external-file: logs/novel-gateway.log
  info:
    env:
      # 公开所有以 info. 开头的环境属性
      enabled: true
